language: python

python: 2.7

env:
  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django15_nosouth
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django_trunk
  - TOX_ENV=py32-django15
  - TOX_ENV=py32-django16
  - TOX_ENV=py32-django17
  - TOX_ENV=py32-django18
  - TOX_ENV=py32-django_trunk
  - TOX_ENV=py33-django15
  - TOX_ENV=py33-django16
  - TOX_ENV=py33-django17
  - TOX_ENV=py33-django18
  - TOX_ENV=py33-django_trunk
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django_trunk

install:
  - pip install --upgrade pip setuptools tox virtualenv

script:
  - tox -e $TOX_ENV

matrix:
  allow_failures:
    - env: TOX_ENV=py27-django_trunk
    - env: TOX_ENV=py32-django15
    - env: TOX_ENV=py32-django16
    - env: TOX_ENV=py32-django17
    - env: TOX_ENV=py32-django18
    - env: TOX_ENV=py32-django_trunk
    - env: TOX_ENV=py33-django15
    - env: TOX_ENV=py33-django16
    - env: TOX_ENV=py33-django17
    - env: TOX_ENV=py33-django18
    - env: TOX_ENV=py33-django_trunk
    - env: TOX_ENV=py34-django17
    - env: TOX_ENV=py34-django18
    - env: TOX_ENV=py34-django19
    - env: TOX_ENV=py34-django_trunk

before_install:
  - pip install codecov

after_success:
  - codecov -e TOX_ENV
