name: CI
on: [push, pull_request]
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        django-version: [ '3.0', '3.1', '3.2', '4.0', '4.1' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install wheel Django==${{ matrix.django-version }}

      - name: Run unit tests
        run: python setup.py test
